spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://35.240.161.100/wallet_mpc?useSSL=false
    username: root
    password: 00000000
    druid:
      # 初始化连接大小
      initial-size: 1
      # 最小连接池大小
      min-idle: 1
      # 最大连接池大小
      max-active: 5
      # 配置获取连接等待超时的时间
      max-wait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 300000
      
  redis:
    host: tc1111.cn
    port: 6379
    password: Sz111111111
    database: 1
    jedis:
      pool:
        max-active: 10
        # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1ms
         # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 5
         # 连接池中的最大空闲连接
        min-idle: 0
         # 连接池中的最小空闲连接
    timeout: 5000
     # 连接超时时间（毫秒）
mybatis:
  configuration:
    map-underscore-to-camel-case: true
signature:
  server: http://35.240.161.100:8081/
app:
  rune-api-key: hSELZlsPfSMLUzCqRWd65Ry968ItujLz0DR9LLzLkUUo8RJS
  prod: false
