spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    #driver-class-name: com.mysql.jdbc.Driver
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1/wallet_mpc?useSSL=false
    username: root
    password: 123456
    druid:
      # 初始化连接大小
      initial-size: 5
      # 最小连接池大小
      min-idle: 5
      # 最大连接池大小
      max-active: 20
      # 配置获取连接等待超时的时间
      max-wait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      filters: stat,wall,log4j
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      
  redis:
    host: 127.0.0.1
    port: 6379
    password: 1111111
    database: 1
    jedis:
      pool:
        max-active: 10
        # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1ms
         # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 8
         # 连接池中的最大空闲连接
        min-idle: 2
         # 连接池中的最小空闲连接
    timeout: 300000
     # 连接超时时间（毫秒）
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.safnect.wallet.mpc.model
  configuration:
    map-underscore-to-camel-case: true
signature:
  server: http://34.142.132.195:8081/
cat20:
  server: https://cat-tracker.ordbit.io/api
app:
  rune-api-key: hSELZlsPfSMLUzCqRWd65Ry968ItujLz0DR9LLzLkUUo8RJS
  prod: false
